markdown: rdiscount
permalink: /:title/
url: http://zhangdeyu.github.io
name: Derek.Zhang
author: Derek
email: imzhangdeyu@126.com
github: zhangdeyu
highlighter: pygments
pygments: true
safe: true
paginate: 20
about: ""
