markdown: rdiscount
permalink: /:title/
url: http://zhangdeyu.github.io
name: Derek.Zhang
author: Derek
qq: 573222434
email: imzhangdeyu@126.com
duoshuo: 
weibo: 2805290830
github: zhangdeyu
pygments: true
safe: true
paginate: 20
about: "这里是Derek的个人博客~"
